export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const ADD_IMAGE_BEGIN = 'ADD_IMAGE_BEGIN'
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS'
export const ADD_IMAGE_ERROR = 'ADD_IMAGE_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_IMAGE = 'HANDLE_IMAGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const GET_USER_BEGIN = 'GET_USER_BEGIN'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const TRANSACTION_BEGIN = 'TRANSACTION_BEGIN'
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS'
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'


export const GET_TRANSACTION_BEGIN = 'GET_TRANSACTION_BEGIN'
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS'


export const VERIFICATION_BEGIN = 'VERIFICATION_BEGIN'
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const SET_STATUS = 'SET_STATUS'

export const REMOVE_FACE = 'REMOVE_FACE'



// console.log(values)